name: infra-texas2010-com

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    restart: ${DOCKER_RESTART:-no}
    ports:
      - '${HTTPS_PORT:-443}:443'
      - '${HTTP_PORT:-80}:80'
    environment:
      DOMAIN: ${DOMAIN}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ${CADDYFILE_PATH:-./Caddyfile}:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - public_net
      - api_net
      # - web_net

  api:
    image: ghcr.io/texas2010/api.home.texas2010.com:latest
    restart: ${DOCKER_RESTART:-no}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    environment:
      SERVICE_NAME: api
      INFRA_LOCATION: ${INFRA_LOCATION}
      DOMAIN: ${DOMAIN}
      ALLOWED_ORIGIN: https://${DOMAIN}
      WATCHTOWER_NOTIFICATIONS_LEVEL: info
    expose:
      - '3000' # container-only; Caddy can reach api:3000
    networks:
      - api_net
      # - backend_net

  # gotham:
  #   image:
  #   restart: ${DOCKER_RESTART:-no}
  #   profiles:
  #     - cloud
  #   environment:
  #     INFRA_LOCATION: ${INFRA_LOCATION}
  #     DOMAIN: ${DOMAIN}

  # game2:
  #   image:
  #   restart: ${DOCKER_RESTART:-no}
  #   profiles:
  #     - cloud
  #   environment:
  #     INFRA_LOCATION: ${INFRA_LOCATION}
  #     DOMAIN: ${DOMAIN}

  watchtower:
    image: containrrr/watchtower
    restart: ${DOCKER_RESTART:-no}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --label-enable
      --interval 300
      --cleanup

  # -- interval 86400 // 1 day

  # dashboard:
  # network: [web_net, api_net]

  # backend1:
  # network: [backend_net, data_net]

  # database:
  # network: [data_net]

networks:
  public_net: {} # Caddy <-> host (published ports)
  # web_net:
  # internal: true
  api_net:
    internal: true
  # backend_net:
  # internal: true
  # data_net:
  # internal: true

volumes:
  caddy_data: {}
  caddy_config: {}
